### ISSUE TITLE
Nodes/NRPE behehind nat

### ISSUE THREAD

**Issue by helmut-hoffer-von-ankershoffen** [sous-chefs/nagios#360]
Hi,

some of the hosts/nodes/containers in our cluster are in a nat'ed subnet only reachable from the chef server via port-forwards, i.e. their IP and port 5666 is not reachable directly by the chef server.

Is is possible to override the IPs of those hosts nagios gathers via chef using some node attributes and configure nagios to use a non-standard port for accessing nrpe again acquired via some node attribute in chef?

best

**Comment by sbotman** [comment]
Hi @helmuthva, I don't know if there are any proxy solutions because my use of nagios is limited. But I do created something similar as you requested by abusing the notes attribute and populating this with: "-P ${proxy_ip_address}"  Then I created a nrpe wrapper script on the nagios server that would execute the nrpe_proxy_command command with the original as parameter. Then your proxy server would need check_nrpe also to target the command behind the proxy. Was a bit of hacking, so I hope that this will help you achieving your goal. Otherwise please contact me and maybe I can sent you some example scripts that might help. 

So the short answer: No, nagios cookbook does not contain this functionality (but I'm open for suggestions :)

Can I close the ticket with this answer?

**Comment by sbotman** [comment]
I'm closing this ticket, please feel free to contact me on gitter if you have still some open questions. https://gitter.im/tas50/nagios
Gr Sander
