### ISSUE TITLE
Error: Host check command 'check-host-alive' specified for host

### ISSUE THREAD

**Issue by joshskains** [sous-chefs/nagios#397]
Getting Error: Host check command 'check-host-alive' specified for host after upgrading nagios from 6.x to 7.x cookbook. Any help please?

**Comment by sbotman** [comment]
Hi @joshskains, I'm on gitter.. https://gitter.im/schubergphilis/nagios please join and I might be able to help you

**Comment by sbotman** [comment]
looks like the attribute default['nagios']['default_host']['check_command'] = 'check-host-alive' is set somewhere and saved on the node object. Within version 7.x of nagios I have renamed this to check_host_alive to be consistent with the naming of checks. But this is now causing problems with upgrading to newer version. Need to do some research on this.

**Comment by sbotman** [comment]
I believe we spoke on this on Gitter and discovered that while migrating from cookbook version 6.x to 7.x it's introducing this bug. Since it's a while back, I don't remember what we have done to fix this. Maybe @joshskains can refresh my memory :)

**Comment by sbotman** [comment]
I remember this one again, this one was due to the fact that the nagios server contained a attribute pointing to the check-host-alive.  Once this one was removed, the problem was fixed.
So once you start a migration of the cookbook, you might want to check the node attribute and remove and conflicting attributes.
