### ISSUE TITLE
check_interval and similar settings render as float

### ISSUE THREAD

**Issue by justizin** [sous-chefs/nagios#419]
Nagios seems to interpret these as minutes instead of seconds, so e.g. instead of 15s, the default intervals are 15min.

```
$ grep interval /etc/nagios3/conf.d/templates.cfg
  check_interval         15.0
  retry_interval         15.0
  notification_interval  300.0
  check_interval        60.0
  retry_interval        15.0
  check_interval                60.0
  retry_interval                15.0
  notification_interval         1200.0
  check_interval         60.0
  retry_interval         15.0
  notification_interval  1200.0
```

This is on Ubuntu 14.04 with chef 12.4.1.

I'm happy to help test variations of my current setup and produce a chefspec test that fails or somesuch, but I wanted to start documenting this as I've spent a good bit of time digging into it.

It seems like there might be code validating this input as an integer, starting in libraries/host.rb:

```
def check_interval=(int)
  @check_interval = check_integer(int)
end
```

which, when i grep around, leads me to an interesting blurb in libraries/_load_default_config.rb:

```
nagios_host 'server' do
  options 'name'                   => 'server',
          'use'                    => 'default-host',
          'check_period'           => nagios_attr(:default_host)[:check_period],
          'check_interval'         => nagios_interval(nagios_attr(:default_host)[:check_interval]),
          'retry_interval'         => nagios_interval(nagios_attr(:default_host)[:retry_interval]),
          'max_check_attempts'     => nagios_attr(:default_host)[:max_check_attempts],
          'check_command'          => nagios_attr(:default_host)[:check_command],
          'notification_interval'  => nagios_interval(nagios_attr(:default_host)[:notification_interval]),
          'notification_options'   => nagios_attr(:default_host)[:notification_options],
          'contact_groups'         => nagios_attr(:default_contact_groups),
          'register'               => 0
end
```

which points me nagios_interval, defined in libraries/default.rb:

```
def nagios_interval(seconds)
  if seconds.to_i != 0 && seconds.to_i < node['nagios']['interval_length'].to_i
    fail ArgumentError, "Specified nagios interval of #{seconds} seconds must ether be zero or be equal to or greater than the default interval length of #{node['nagios']['interval_length']}"
  end
  interval = seconds.to_f / node['nagios']['interval_length']
  if interval != interval.to_i
    fail ArgumentError, "Specified nagios interval of #{seconds} seconds must be a multiple of the interval length of #{node['nagios']['interval_length']}"
  end
  interval
end
```

Seems to me like it's passing a number of tests, it's not really clear how it ends up rendering as a float, or if I am somehow doing something that causes this.  I'm happy to share my wrapper cookbook, which basically just includes the nagios cookbook and sets a couple of default attributes related mostly to the apache config.

**Comment by sbotman** [comment]
Well, this part of code is quite old and may need some updating. Reading the documentation and the logic within the function, I think that the idea was to correct the user input and making it so that the input is always in seconds. And this function would convert the input into minutes (according to the interval_length setting)

So if my node['nagios']['interval_length'] = 60 (sec)
And you specify 300 seconds, the result will be: 300 / 60 = 5
So: 5 \* (interval_length)

But if the node['nagios']['interval_length'] = 120 (sec)
And you specify 360 seconds, the result will be: 300 / 120 = 3, 
So: 3 \* (interval_length)

But this is only with the default_config. I need to check what will happen when you specify this number externally..

So good point you are making here Justin...
This will need some more investigation (when time permits I will try to dive into this)

Gr Sander

**Comment by justizin** [comment]
Interesting stuff, let me know how I can help!

**Comment by sbotman** [comment]
I think that I have broken this when I moved all the nagios attributes into the config.rb attribute file and added the ['conf'] section to all attributes. Because while I was doing that, I have put the interval_length on 60 (the default), while it was 1. 1 would mean 1 second and would mean that all inputs would be treaded as seconds and solve the problem. But then I was look at the nagios_interval function and I don't understand the logic in there. Think that this is something very old, but will investigate or will try to reach out to the creators because would like to understand the reasoning behind it. Think that chancing the function to something like this would be the solution:

```
def nagios_interval(seconds)
  return 0 if node['nagios']['conf']['interval_length'].to_i == 0
  seconds.to_f / node['nagios']['conf']['interval_length']
end
```

But this might be to simple and I might be overlooking something :wink:

**Comment by justizin** [comment]
I'm happy to try putting that in a branch in my fork and give it some testing, when I get the time.

**Comment by justizin** [comment]
BTW, looking into this again today, but it's still unclear why some values render as decimal, and how that can be prevented.

Maybe there are two issues: one with the rendering of the values, another with the default values themselves.

**Comment by sbotman** [comment]
Think that it is better that we remove the logic and force the interval_lenght to 1 second (we use this internal and works fine). This way the whole checking of the value doesn't need to be done...

**Comment by sbotman** [comment]
@bitmonk, is PR #433 something that will work for you?

**Comment by justizin** [comment]
I'm still confused as to how they ended up rendering as float, but that has seemed to have stopped, and at a glance, it looks sensible.  Hooray!

**Comment by sbotman** [comment]
In the old code:

```
def nagios_interval(seconds)
  if seconds.to_i != 0 && seconds.to_i < node['nagios']['interval_length'].to_i
    fail ArgumentError, "Specified nagios interval of #{seconds} seconds must ether be zero or be equal to or greater than the default interval length of #{node['nagios']['interval_length']}"
  end
  interval = seconds.to_f / node['nagios']['interval_length']
  if interval != interval.to_i
    fail ArgumentError, "Specified nagios interval of #{seconds} seconds must be a multiple of the interval length of #{node['nagios']['interval_length']}"
  end
  interval
end
```

The `interval = seconds.to_f / node['nagios']['interval_length']` converted the interval into a float. So all interval's were rendered as float.

**Comment by justizin** [comment]
thanks for breaking it down @sbotman and thanks for the fix! :100:
