### ISSUE TITLE
Additional items for pagerduty integration

### ISSUE THREAD

**Issue by ovaistariq** [sous-chefs/nagios#435]
The perl-CGI package and the pagerduty.cgi scripts need to be setup for two-way pager duty integration.

**Comment by sbotman** [comment]
This solution breaks the installation on ubuntu, so I guess you are using Redhat/Centos as your distro

```
           ================================================================================
           Error executing action `install` on resource 'apt_package[perl-CGI]'
           ================================================================================

           Chef::Exceptions::Package
           -------------------------
           No candidate version available for perl-CGI

       Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/nagios/recipes/pagerduty.rb

            33: package 'perl-CGI' do
            34:   action :install
            35: end
            36:
```

Wondering if this package is really needed for the pagerduty perl script, but if this is the case, we should also add the right package name for ubuntu. Maybe @tas50 can help out here because he has more experience with ubuntu boxes.

**Comment by ovaistariq** [comment]
My bad that I didn't test in Ubuntu
