### ISSUE TITLE
Error: Host 'server' specified in host group 'linux' is not defined anywhere!

### ISSUE THREAD

**Issue by ikrauchanka** [sous-chefs/nagios#452]
Hi,
I have a server with hostname server.myco.com. This server was bootstrapped with knife + manage.chef.io.When I run chef-client  it fails on nagios reload.
Nagios checkconfig shows:

``` ruby
Checking host groups...
Error: Host 'server' specified in host group 'linux' is not defined anywhere!
Error: Host 'server' specified in host group 'prod' is not defined anywhere!
    Checked 4 host groups.
```

```
hostgroups.cfg:
define hostgroup {
  hostgroup_name all
  alias all
  members *
}

define hostgroup {
  hostgroup_name  linux
  members         ip-172-31-60-118,server
}

define hostgroup {
  hostgroup_name  monitoring
  members         ip-172-31-60-118
}

define hostgroup {
  hostgroup_name  prod
  members         ip-172-31-60-118,server
}
```

But when I set different environment for server - chef-client complete successfully.

What I have to do if I have a bunch of hosts with : 
1. server.*
2. server.myenv.domain.com
3. server2.mysql.myenv.domain.co.za
?

thanks!

**Comment by sbotman** [comment]
I guess you found the solution before I found some time to react to this :+1: 
Think this is related to the fact that the default is using server as template name, hence it cannot be used.
If you name your servers differently, like svr01, svr02, etc, etc.. all should be fine.

**Comment by ikrauchanka** [comment]
Hello Sander,
I guess you're very busy. Your cookbook is great workable solution to mitigate the pain with adding/removing ec2 when they are under autoscalling and born and die each minute.
But one thing what we need is proper documentation for not highly skilled users in chef.
Yes, I can read what you meant in libraries, but there are some places where it is not so easy to understand, for example with custom services and their definitions in recipe, not in data bag.
Could you please find a hour and extend existing wiki with proper examples or even share workable wrapped cookbook with various checks, hosts, services, relations. Thank you in advance. 

PS
A pint of beer from me.

**Comment by sbotman** [comment]
Hi Illia, 

I was indeed quite occupied this week. Also the nagios cookbook is more like a private project, because it's not directly connected to my work at this moment. Initial the cookbook was created by other peeps/companies, so really cannot take credit for this. The fact that it's hard to read for staring chef-users and missing examples is totally my fault! I did try to add wrapper examples to the wiki and added documentation about the services, but I agree with you that it needs more structure. Maybe you can explain me your current challenges or configuration pain that you experience at the moment, so we can add that information to the wiki so it will also benefit others.

Please join me on gitter https://gitter.im/schubergphilis/nagios and lets writeup some docs..
