### ISSUE TITLE
unmanagedhosts

### ISSUE THREAD

**Issue by jopelope** [sous-chefs/nagios#489]
Hello,

I have a question about unmanagedhosts data bags. The doc says `Similar to services, you may also filter unmanaged hosts by environment.`, but the code in _load_databag_config.rb does something different:

```
  if node['nagios']['multi_environment_monitoring']
    envs = node['nagios']['monitored_environments']
    next if item['environment'].nil? || !envs.include?(item['environment'])
  else
    next if item['environment'].nil? || item['environment'] != node.chef_environment
  end
```

If there is no environment set for the host it will never be added. Is this a bug or am I understanding the doc wrong?

Thanks.

**Comment by nkadel-skyhook** [comment]
As best I can tell, this is expected behavior. It makes use of this cookbook quite awkward for chef-solo environments, with no chef server enabled but a list of well defined nodes in a local git repository. You basically have to add individual recipes and templates from _another_, locally maintaned cookbook, in order to link such a chef-solo based Nagios server to designated remote targets.

**Comment by cole-christensen** [comment]
+1 this is a bug because it's unreasonable behavior having to do with the handling of multiple environments

**Comment by plopezpivotal** [comment]
+1 this is a bug. In my case I was not using the environments and this was working as expected previously.

I worked around the issue by updating data bag item with:

"environment": "_default",

since node.chef_environment is _default .
next if item['environment'].nil? || item['environment'] != node.chef_environment.
