### ISSUE TITLE
Release working Cookbook.

### ISSUE THREAD

**Issue by damacus** [sous-chefs/nagios#526]
We need to do a clean release with Sous-Chefs and recent fixes.

**Comment by tas50** [comment]
You're setting high standards here

**Comment by damacus** [comment]
😂 figure, aim for the moon

**Comment by jbexten** [comment]
The current version of the cookbook released to the supermarket is not compatible with Nagios 4+ due the changes to the apache cookbook. It appears that those issue are resolved in the source, but without a release we cannot pull them in via berks. A working release would be appreciated.

**Comment by sirosen** [comment]
Hate to nag, but... \<nag\> Is there a timeline for a release?

We have a couple of outstanding pieces of work blocked on a new version of this cookbook (because it's blocking an update from nginx to chef_nginx by means of #525 ).
\</nag\>

**Comment by seren** [comment]
Just to keep this issue alive, we've been blocked waiting for the fixes in the next version.

**Comment by damacus** [comment]
I really need to find some time to set aside and sit down to do this.

Any help would be appreciated!

**Comment by tas50** [comment]
At this point we just need a well written changelog

**Comment by seren** [comment]
Would that just be a list of the issues closed due to merges since 71cba61 on Dec 14, 2015, grouped into bugs and improvements?

It looks like there are [about 20 of them](https://github.com/sous-chefs/nagios/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20closed%3A%3E2015-12-14), though I suppose there could be multiple bugs/improvements per issue, and maybe some that aren't referenced by issue but PR instead (there seem to be [30 merged PRs](https://github.com/sous-chefs/nagios/pulls?utf8=%E2%9C%93&q=is%3Apr%20is%3Amerged%20merged%3A%3E%3D2015-12-14)).

**Comment by tas50** [comment]
Shipping!
